using HRPortal.Data;
using HRPortal.Models;
using HRPortal.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
namespace HRPortal.Controllers;
public class OrganizationController(HRPortalDbContext db,OrganizationService service):Controller
{
 public async Task<IActionResult> Index(int? revisionId)
 {
  var revisions=await service.RevisionsAsync();var current=revisionId.HasValue?revisions.FirstOrDefault(x=>x.Id==revisionId):await service.CurrentAsync();
  if(current!=null){var nodes=await db.OrganizationNodes.Where(x=>x.OrganizationStructureRevisionId==current.Id).OrderBy(x=>x.SortOrder).ThenBy(x=>x.Title).ToListAsync();var map=nodes.ToDictionary(x=>x.Id);foreach(var n in nodes){n.Children=new List<OrganizationNode>();}foreach(var n in nodes.Where(x=>x.ParentId.HasValue)){if(map.TryGetValue(n.ParentId!.Value,out var parent))parent.Children.Add(n);}current.Nodes=nodes;}
  ViewBag.Revisions=revisions;return View(current);
 }
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> NewRevision(string effectiveDate,string title,string? notes){if(!PersianDateService.TryParse(effectiveDate,out var date)){TempData["Error"]="تاریخ اجرا را به صورت شمسی مانند ۱۴۰۵/۰۷/۰۵ وارد کنید.";return RedirectToAction(nameof(Index));}await service.CreateRevisionAsync(date,title,notes);return RedirectToAction(nameof(Index));}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> AddNode(int revisionId,int? parentId,string code,string title,string rankType,int sortOrder=0,string? notes=null){var r=await db.OrganizationStructureRevisions.FindAsync(revisionId);if(r==null||r.IsFinalized){TempData["Error"]="فقط نسخه در حال ویرایش قابل تغییر است.";return RedirectToAction(nameof(Index),new{revisionId});}db.OrganizationNodes.Add(new OrganizationNode{OrganizationStructureRevisionId=revisionId,ParentId=parentId,Code=code,Title=title,RankType=rankType,SortOrder=sortOrder,Notes=notes});db.OrganizationChanges.Add(new OrganizationChange{OrganizationStructureRevisionId=revisionId,ChangeType="افزودن",EntityCode=code,Description=$"افزودن {title}"});await db.SaveChangesAsync();return RedirectToAction(nameof(Index),new{revisionId});}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> EditNode(int id,string code,string title,string rankType,int sortOrder,string? notes){var n=await db.OrganizationNodes.Include(x=>x.Revision).FirstOrDefaultAsync(x=>x.Id==id);if(n==null)return NotFound();if(n.Revision.IsFinalized){TempData["Error"]="نسخه نهایی قابل ویرایش نیست؛ ابتدا نسخه جدید ایجاد کنید.";}else{n.Code=code;n.Title=title;n.RankType=rankType;n.SortOrder=sortOrder;n.Notes=notes;db.OrganizationChanges.Add(new OrganizationChange{OrganizationStructureRevisionId=n.OrganizationStructureRevisionId,ChangeType="ویرایش",EntityCode=code,Description=$"ویرایش {title}"});await db.SaveChangesAsync();}return RedirectToAction(nameof(Index),new{revisionId=n.OrganizationStructureRevisionId});}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> DeleteNode(int id){var n=await db.OrganizationNodes.Include(x=>x.Revision).FirstOrDefaultAsync(x=>x.Id==id);if(n==null)return NotFound();if(n.Revision.IsFinalized||!await service.CanDeleteAsync(id)){TempData["Error"]="حذف مستقیم مجاز نیست؛ گره استفاده‌شده یا دارای زیرگره را حذف نمی‌توان کرد.";}else{db.OrganizationChanges.Add(new OrganizationChange{OrganizationStructureRevisionId=n.OrganizationStructureRevisionId,ChangeType="حذف",EntityCode=n.Code,Description=$"حذف {n.Title}"});db.OrganizationNodes.Remove(n);await db.SaveChangesAsync();}return RedirectToAction(nameof(Index),new{revisionId=n.OrganizationStructureRevisionId});}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> Finalize(int revisionId){try{await service.FinalizeAsync(revisionId);}catch(Exception ex){TempData["Error"]=ex.Message;}return RedirectToAction(nameof(Index),new{revisionId});}
}